### ISSUE TITLE
Text colors are not correct in VSCODE

### ISSUE THREAD

**Issue by cilerler** [knsv/mermaid#570] opened 2017-09-07 02:11 UTC
As you can see it in the screenshot, `ALT`,`OPT`,`LOOP` titles are not visible. _(text is there, it is just a dark color which makes it very difficult to read on dark theme.)_

![2017-09-06_22-07-10](https://user-images.githubusercontent.com/385958/30142632-ee85784c-934f-11e7-83c6-6004e01ccccc.png)

**Comment by tylerlong** [comment] 2017-09-25 03:52
Mermaid has a dark theme which is suitable for dark backgrounds.  https://unpkg.com/mermaid@7.0.0/dist/mermaid.dark.css

Not sure who developed the VS Code extension. You can tell the author to add a feature to switch mermaid theme.

**Comment by cilerler** [comment] 2017-09-25 11:48
Thanks

**Comment by mjbvz** [comment] 2017-09-25 19:56
I'm the author of the VSCode mermaid markdown extension. We do use the `mermaid.dark.css` stylesheet but I still don't see the colors being overridden properly. The root cause seems to be that the generated svg uses an inline style:

<img width="714" alt="screen shot 2017-09-25 at 12 50 35 pm" src="https://user-images.githubusercontent.com/12821956/30827853-635a0fbc-a1f0-11e7-82f7-cac41e71ee61.png">

which overrides the dark css' `.looptext` and `.labelText` rules. Are there other steps required to use the dark theme?

**Comment by tylerlong** [comment] 2017-09-26 05:16
Things have changed since 7.1.0.

https://github.com/mermaidjs/mermaid-live-editor/blob/master/src/index.js#L8

In earlier versions you specify a CSS file. After 7.1.0 you just specify an option. And yes styles are inline.

**Comment by vstirbu** [comment] 2017-09-26 16:50
Hello, I'm maintaining another vscode mermaid extension and we have the same issue although the extension is selecting correctly the theme: https://github.com/vstirbu/vscode-mermaid-preview/issues/41.

The extension is using mermaid 7.1.0 so no way to mangle CSS files. We would appreciate if this issue is fixed in mermaid itself, rather than comping with hacks downstream :).

**Comment by tylerlong** [comment] 2017-09-26 17:00
For now, is it possible for your guys to add `window.mermaid_config = { theme: 'dark' }` if you are using 7.1.0 ?

I am still doing lots of refactoring at the moment. If you want the old behavior, just use 7.0.0.

I will figure out the best solution before 8.0.0

**Comment by vstirbu** [comment] 2017-09-26 17:10
For the record, the problem is with the color of the text in the loops and alts. Even when using the dark theme, that text is black that not visible in the dark:
![screen shot 2017-09-26 at 20 05 29](https://user-images.githubusercontent.com/1288047/30873608-7e1636da-a2f6-11e7-9a94-4a757423c0e6.png)

Appreciate all the renovation work that you do, and waiting for 8.0.0...

**Comment by arjunachala** [comment] 2017-09-27 16:43
I have used the dark theme of Mermaid. It seems to be working except for the arrows at the end of the connectors. You can see it here:

![image](https://user-images.githubusercontent.com/999180/30925842-4560dc1a-a381-11e7-9a06-95ebdf85312f.png)

I am using the 7.0 codebase as suggested on this thread. Any help is appreciated. Thank you!

**Comment by cilerler** [comment] 2017-09-27 16:57
@arjunachala please don't hi-jack the subject.   This is about text and not shapes.  Create another issue for that one please.

**Comment by arjunachala** [comment] 2017-09-27 22:40
sorry about that! opened another issue at - https://github.com/knsv/mermaid/issues/578

**Comment by mjbvz** [comment] 2017-10-09 17:44
I've tried updating the VSCode extension to use 7.1,  but even after passing in `theme: 'dark'` I don't see loops being styled properly. 

@tylerlong Side note: using external style vs inline is also preferable for our use case since we allow dynamically changing styles. Not sure how to do that without a re-render currently

**Comment by bnacey** [comment] 2018-02-14 17:08
Has there been any progress on this issue?

**Comment by tylerlong** [comment] 2018-03-16 12:59
Please try the latest version: 
![image](https://user-images.githubusercontent.com/733544/37521686-8f28c658-295c-11e8-9aaf-024859dcfaff.png)

It's not beautiful but I am a developer instead of a UI designer.

And you want to change the colors, simply change this file and send me a PR: https://github.com/knsv/mermaid/blob/master/src/themes/dark/index.scss

You can even create a new theme by creating a new file like above.

**Comment by tylerlong** [comment] 2018-03-22 01:27
Now it is also possible to write CSS to override CSS in theme: https://github.com/mermaidjs/mermaid.cli/pull/24#issuecomment-373402785

**Closed by tylerlong** 2018-03-22 01:27 UTC
