### ISSUE TITLE
Online Editor fails to show exported SVG

### ISSUE THREAD

**Issue by LarsGottlieb** [knsv/mermaid#601] opened 2017-12-06 12:48 UTC
Online editor 7.1.0 Cannot view this graph as SVG: 
Error: error on line 360 at column 14377: Opening and ending tag mismatch: br line 0 and span

graph TD
 Scripts-->|Opret, ret og slet|retinfopctabel
epbtabeller-->|Overvågning aflæser vw_AlarmView|Overvågning
spsynkservice-->|Overvågning monitorer at <br/>service er kørende|Overvågning
  Bruger-->website
  subgraph Windows server
   subgraph Retinfo database
   retinfopctabel[RetinfoPcere]-->|Trigger på tabel|retinfopcko[pc-ændringskø]
   end
 subgraph EPIC Print Byg database
retinfopcko-->|Synkronisering|epbpcko[pc ændringskø]
epbpcko-->|Epic Print Byg core<br/>henter pc ændringer|epbtabeller[Epic Print Byg core]

  epbtabeller-->sptabel[EPR, LWS og LOM kø tabeller]
  epbtabeller-->adtabel[AD kø tabel]
 end
end
subgraph Windows server
 website[EPIC Print Byg website]-->epbtabeller
 website-->retinfopctabel
end

subgraph Windows server
filesystem[Filesystem]-->|EPIC Print Byg website<br/> <b>henter</b> organisationsdata|website
 end
subgraph Windows server
 ad[AD]-->addb[AD store]
end
subgraph Windows server
 day[Daglig job]-->|Synkroniser gruppemedlemskaber<br/>for alle pc'ere fra<br/>EPIC Print Byg med AD|ad
 adtabel-->|Hent pc-AD-gruppemedlemskabs-<br/>ændringer fra kø|adko
 adko[Kø job]-->|Tilføj/fjern pc<br/>fra AD-grupper|ad
epbtabeller-->|Hent alle pcers medlemskaber|day
sptabel-->|EPIC synkroniseringsservice<br/>henter fra kø-tabeller|spsynkservice[EPIC synkroniseringsservice]
end

subgraph Unix server
 subgraph EPIC
 spsynkservice-->|EPIC synkroniseringsservice<br/>screenscraper til LOM og<br/> fileimporter til LWS og EPR|chronicle[Chronicle]
 end
end

**Comment by tylerlong** [comment] 2018-03-13 14:18
Duplicate of https://github.com/knsv/mermaid/issues/614 which has been resolved.

If you still have this issue, please create a new issue. Please do include a link to https://mermaidjs.github.io/mermaid-live-editor/ so I can click to open your diagram.

**Closed by tylerlong** 2018-03-13 14:18 UTC
