### ISSUE TITLE
flowchart - nodes containing escape characters are rendered weirdly

### ISSUE THREAD

**Issue by olindk** [knsv/mermaid#398] opened 2016-10-14 10:25 UTC
Hi there!

Nodes containing escape characters are rendered with lots of empty space at the end.

For example, the following code"

> graph LR
>         A["A double quote:#quot;"]

will render like this:

```
**********************
*A double quote:"    *
**********************
```

Instead, It would be nice to render like this:

```
******************
*A double quote:"*
******************
```

What do you think?

**Comment by ajrnz** [comment] 2016-12-18 11:10
Same here. It looks like the width of the box is being calculated from the width of the string which includes the escape sequence. So in something like this:

    graph TD;
        A["#65;#65;#65;"] --- AAA

the width of the first box is about 3 times the size of the second.

**Comment by tylerlong** [comment] 2018-03-17 13:07
I confirm that this is an issue. And it is caused by the text width calculation method. It measures the text width before rendering.  `#quot;` is much wider than `"`

**Comment by bebuch** [comment] 2019-09-04 08:38
This bug still exists and is very annoying.

**Comment by bebuch** [comment] 2019-09-04 18:25
It can be fixed by removing the masking stuff. 

The tests all continue to work and the test renderings remain unchanged.

@knsv I don't know where the masking stuff is good for. Can you take a look at it please?

```patch
diff --git a/src/mermaidAPI.js b/src/mermaidAPI.js
index 22aeadc..abd00a1 100644
--- a/src/mermaidAPI.js
+++ b/src/mermaidAPI.js
@@ -316,7 +316,7 @@ function parse (text) {
   parser.parse(text)
 }
 
-export const encodeEntities = function (text) {
+const encodeEntities = function (text) {
   let txt = text
 
   txt = txt.replace(/style.*:\S*#.*;/g, function (s) {
@@ -333,30 +333,15 @@ export const encodeEntities = function (text) {
 
     const isInt = /^\+?\d+$/.test(innerTxt)
     if (isInt) {
-      return 'ﬂ°°' + innerTxt + '¶ß'
+      return '&#' + innerTxt + ';'
     } else {
-      return 'ﬂ°' + innerTxt + '¶ß'
+      return '&' + innerTxt + ';'
     }
   })
 
   return txt
 }
 
-export const decodeEntities = function (text) {
-  let txt = text
-
-  txt = txt.replace(/ﬂ°°/g, function () {
-    return '&#'
-  })
-  txt = txt.replace(/ﬂ°/g, function () {
-    return '&'
-  })
-  txt = txt.replace(/¶ß/g, function () {
-    return ';'
-  })
-
-  return txt
-}
 /**
  * Function that renders an svg with a graph from a chart definition. Usage example below.
  *
@@ -496,8 +481,6 @@ const render = function (id, txt, cb, container) {
   // Fix for when the base tag is used
   let svgCode = d3.select('#d' + id).node().innerHTML.replace(/url\(#arrowhead/g, 'url(' + url + '#arrowhead', 'g')
 
-  svgCode = decodeEntities(svgCode)
-
   if (typeof cb !== 'undefined') {
     switch (graphType) {
       case 'flowchart':
```

**Comment by bebuch** [comment] 2019-10-21 18:59
Still not fixed and highly relevant. @knsv Please reopen.

**Comment by Dunning-Kruger** [comment] 2019-10-21 19:20
@bebuch Hey, I believe this is the same issue reported on #975. If not, please provide a link to a live editor with a reproduction. Thank you.

**Comment by bebuch** [comment] 2019-10-22 09:03
@Dunning-Kruger You are right, thanks!

**Comment by Dunning-Kruger** [comment] 2019-10-22 13:21
Duplicate of #975

**Closed by Dunning-Kruger** 2019-10-22 13:21 UTC
