### ISSUE TITLE
All <svg> elements in page are colored black

### ISSUE THREAD

**Issue by rhysd** [knsv/mermaid#584] opened 2017-10-08 04:33 UTC
### Problem

I found a weird CSS rule in `<style>` element under `<svg id="mermaidChartXXX">` element as following.

```css
svg {
  color: rgb(0, 0, 0);
  font: normal normal normal normal 16px / normal "Hiragino Kaku Gothic ProN";
}
```

It colors all `<svg>` elements as black in an entire page overwriting other CSS rules.

### How to reproduce

1. Install mermaid with `$ npm install mermaid`
2. Open example page with `$ open node_modules/mermaid/dist/index.html`
3. Find `<svg id="mermaidChart1">` element under `<div class="mermaid">`
4. Check child `<style>` element's last CSS rule.

### Environment

Followings are my environment information:

- macOS 10.12.6
- Chrome 61.0.3163.100
- mermaid 7.1.0

**Comment by rhysd** [comment] 2017-10-08 09:17
It seems that this does not occur in mermaid 7.0.0. So this is a regression.

**Comment by tylerlong** [comment] 2017-10-09 04:46
Yes it is a regression.

In order to fix the problem from the root, we need to put mermaid CSS into its own namespace so it won't have any global pollution effect.

Example:

```css
.mermad > svg {
...
}
```

**Comment by sclarson** [comment] 2017-11-07 16:45
This looks like it is resolved by: https://github.com/knsv/mermaid/pull/577

**Closed** 2018-03-17 15:40 UTC
