### ISSUE TITLE
Problem wit click event callback

### ISSUE THREAD

**Issue by gameshirtz** [knsv/mermaid#174] opened 2015-06-11 13:56 UTC
Hi,

thanks for the super cool mermaid.
I have a questions, because i have problems to set a click event to a Node.

Graph Code:

            graph LR
            ABC(Datasource) -- Input --> B((System))
            B -- Output --> C(Datasink)

            click ABC testc

JS Code:

      function testc(id){
        window.location.href = 'http://www.google.de';
      }

The callback function testc is not triggerd. What i have to to to get a click Event on the ABC node, so it will open the google website? Thank you!

**Comment by knsv** [comment] 2015-06-14 12:46
I could replicate the issue with a page that contains several diagrams and found a root cause the issue which I fixed. A side effect will be that on a page with several diagrams if the node ids are not unique a click could be mapped to several nodes.

**Comment by gameshirtz** [comment] 2015-06-15 12:04
Thank you, i will test it.

**Comment by knsv** [comment] 2015-06-21 15:48
Fixed with release 0.5.1

**Closed by knsv** 2015-06-21 15:48 UTC
