### ISSUE TITLE
module.exports.cloneCssStyles() in combination with Angularjs breaks display in Chrome and IE

### ISSUE THREAD

**Issue by wolframst** [knsv/mermaid#126] opened 2015-03-05 12:10 UTC
Hi Knut,

Thanks for this great library! It is really easy and intuitive to use.

I am using mermaid together with Angularjs, what works fine by and large.
When testing in different browsers, I noticed one issue that breaks display of Flowcharts in Chrome (latest version) and IE 10. In both browsers, all chart items appear completely black.
Uncommenting the lines below fixed the issue.

```javascript
module.exports.cloneCssStyles = function(svg, classes){
  ...
  if (typeof(rule.style) !== 'undefined') {
    var elems = svg.querySelectorAll(rule.selectorText);
      if (elems.length > 0) {
        usedStyles += rule.selectorText + " { " + rule.style.cssText + " }\n";
      }
  }
  ...
}
```

The Javascript error is
```javascript
Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate)' is not a valid 
selector.
```

Searching for the problem, I found one link to a similar issue on github. The developer says that handling of invalid selector errors fixed the issue here. ( https://github.com/exupero/saveSvgAsPng/issues/11 )

Uncommenting the code did not have any negative impact on display, so this is a workaround for me.
Maybe you can provide a fix in one of the next versions?

Thanks,
Wolfram

**Comment by knsv** [comment] 2015-03-05 22:21
Thanks for pointing this out. I will look into it!

Skickat från min iPad

**Comment by knsv** [comment] 2015-03-07 12:37
The similar issue you sent was very useful. I have wrapped the css copying in a try/catch statement in a similar way. This is committed but not yet released. It also handles the case when the css file is on an external site, then firefox blocks the css copying.

@wolframst, it would be very useful if you could test and see if this solves your issue.

**Comment by wolframst** [comment] 2015-03-09 08:28
Hi Knut,

Thats what I call a fast response. Thanks so much!
The fix resolved the issue partially. The graph now renders, but all edges are missing. Looks like the invalid selectors error gets thrown while rendering the edges.
In order to reproduce the issue it should be sufficient to incude the angular.js file.

Best,
Wolfram

**Comment by knsv** [comment] 2015-03-10 19:19
That sounds like a styling issue. Check if the styles for edgePaths are in place. 
```
.edgePath .path {
   stroke: #333333;
}
```

Also is the same for firefox/chrome?

A tmp addition of the style inline can also give some clues to what the problem is.

**Comment by knsv** [comment] 2015-06-07 15:45
A fix for this has been released in version 0.5.0

**Closed by knsv** 2015-06-07 15:45 UTC

**Comment by ma-zal** [comment] 2015-06-08 06:16
I updated Mermaid to 0.5.0. But error still appears. :(
Using AngularJS v1.3.15.

**Comment by knsv** [comment] 2015-06-08 17:26
This is an error message occurring when styles are being copied from the surround context, (web page), into the svg code.  

The css rules that fails are, (at least in my test page), related to angular and not to the svg. In the catch clause for the exception there error is written but the copying continues.

Does the svg appear for you?

/Knut
--  
Knut Sveidqvist
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ma-zal** [comment] 2015-06-09 09:13
To knsv: You are right, final SVG is OK. So, if i understand, this "error" is "warning" only, because all works. And my imagination is: Error causes some part of Angular, that tries to manipulate with DOM, and it is not possible to solve it.
