### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pezholio** [knsv/mermaid#189] opened 2015-07-21 09:44 UTC
I'm generating a quite complex flowchart, and I get the above error. It seems be be caused by the `showPosition` function. The flowchart generates OK, but the error means that the text used to generate the flowchart is not hidden. Is there any way to skip this function call? (without editing the underlying code)

**Comment by knsv** [comment] 2015-09-28 06:55
Sorry for late response. How large is this diagram? Have not been able to reproduce the issue?

**Comment by tylerlong** [comment] 2018-03-13 14:39
Close it since no more feedback.

**Closed by tylerlong** 2018-03-13 14:39 UTC
