### ISSUE TITLE
lower case v causes error in the parser

### ISSUE THREAD

**Issue by timelyportfolio** [knsv/mermaid#108] opened 2015-01-20 15:34 UTC
It appears `v` anywhere inside the diagram spec will cause the parser to fail.  As an example,
`graph LR; v;` fails while `graph LR; V;` works just fine.

ref https://github.com/rich-iannone/DiagrammeR/issues/47

**Comment by timelyportfolio** [comment] 2015-01-20 18:01
updated to say any "v" in spec causes an error

**Comment by knsv** [comment] 2015-01-20 19:25
Fixed the problem, it will be included in the next release. Root cause was that the character v is also used for direction down

**Comment by timelyportfolio** [comment] 2015-01-21 15:39
I see the fix and the test passes.  However, this `graph LR; v;` still does not work.  Should I expect this or just know that `v` is a reserved character.

**Comment by knsv** [comment] 2015-01-25 16:16
Missed this one or I would have included this in 0.3.3. 

I have added v as a valid for ids so with the next release this will work. Perhaps we should sum things up and do bigger fix for the characters. Right now its one at a time when they pop up.

**Comment by vijay40** [comment] 2015-01-29 05:35
The wiki should be updated to reflect that direction of graph can also be specified by >,<,^,v.

**Comment by knsv** [comment] 2015-03-01 16:06
This si working in the mermaid version 0.4.0. Closing this issue. Reopen if this till is a problem.

**Closed by knsv** 2015-03-01 16:06 UTC

**Comment by timelyportfolio** [comment] 2015-03-09 16:33
Sorry to be a pain, but...

`graph TD; v-->a;`  still does not work
`graph TD; V[v]-->a;` does

**Comment by knsv** [comment] 2015-03-10 19:21
I agree, will look at it. It is a "keyword" but perhaps the grammar could allow this keyword.
