### ISSUE TITLE
Styling subgraph?

### ISSUE THREAD

**Issue by sinedied** [knsv/mermaid#391] opened 2016-09-30 09:52 UTC
It would be nice to be allow to style `subgraph`, the same way we can style nodes, for example like this to change subgraph background color:

```
graph TD
  subgraph A
    B-->C
    B-->D
    C-.-D
  end
  D-->E
  classDef red fill:#fdc
  class A red
```

What do you think?

**Comment by knsv** [comment] 2016-09-30 10:52
I think its a great feature! And it is a great small functionality to start with for someone who want to to try to contribute.

**Comment by WalshJP** [comment] 2017-01-08 19:51
I'll take this feature!

**Comment by knsv** [comment] 2017-01-09 20:21
That stunds great. It's yours!

**Comment by yech1990** [comment] 2017-03-20 14:28
Is that finished yet?

**Comment by tscislo-lingaro** [comment] 2017-04-14 08:28
Any progress on this?

**Comment by MoeweX** [comment] 2017-05-21 08:50
Also interested, any progress yet?

**Comment by pchaganti** [comment] 2017-05-21 11:24
👍

**Comment by joeto0** [comment] 2017-11-02 18:39
any news?

**Comment by beardedeagle** [comment] 2018-02-20 17:10
where are we with this?

**Comment by kbsizer** [comment] 2018-03-30 22:51
This would **_really_** be handy about now.  
Any hope of adding this soon-ish?

**Comment by djoffe** [comment] 2018-05-24 12:56
@knsv This would be a really handy feature, but it does not look like @WalshJP is aware this is assigned to him...
Maybe remove the `assigned` tag and put it back for grabs?

**Comment by TKappatsch** [comment] 2019-02-08 11:21
Need it here as well

**Comment by fchiorascu** [comment] 2019-02-20 12:29
+

**Comment by omerbensa** [comment] 2019-02-20 18:55
Bump

**Comment by ianqueue** [comment] 2019-05-22 19:40
Bump

**Comment by Qix-** [comment] 2019-05-24 12:23
Here's the downside: subgraph titles are also their IDs in OP's case. There would have to be a change to the DSL, something like:

```mermaid
subgraph some-id[Some Subgraph]
...
end
```

**Comment by Qix-** [comment] 2019-05-26 10:52
Submitted #845, which adds styling. Unfortunately, the maintainer seems to be absent.

**Comment by knsv** [comment] 2019-05-28 20:21
Wow! A fix for this one, wonderful!

**Closed** 2019-05-28 20:22 UTC
Labels: assigned

**Comment by fbertoia** [comment] 2019-12-31 10:16
Why this issue has been closed ? It is not yet fixed, isn't it ?

**Comment by chris579** [comment] 2019-12-31 10:39
It meant to be closed with #845. If this issue persists for you please create a new one with a reproduction sample.
